-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

BEGIN;

CREATE SCHEMA IF NOT EXISTS staging;

CREATE TABLE IF NOT EXISTS staging."softcartDimDate"
(
    dateid integer,
    "date" date,
    "year" integer,
    quarter integer,
    quartername character varying(2),
    month integer,
    monthname character varying(10),
    day integer,
    weekday integer,
    weekdayname character varying(10),
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS staging."softcartDimCategory"
(
    categoryid integer,
    category character varying(10),
    PRIMARY KEY (categoryid)
);

CREATE TABLE IF NOT EXISTS staging."softcartDimItem"
(
    itemid integer,
    item character varying(10),
    PRIMARY KEY (itemid)
);

CREATE TABLE IF NOT EXISTS staging."softcartDimCountry"
(
    countryid integer,
    country character varying(100),
    PRIMARY KEY (countryid)
);

CREATE TABLE IF NOT EXISTS staging."softcartFactSales"
(
    dateid integer,
    orderid integer,
    categoryid integer,
    itemid integer,
    countryid integer,
    price money,
    PRIMARY KEY (orderid)
);

ALTER TABLE IF EXISTS staging."softcartFactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES staging."softcartDimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS staging."softcartFactSales"
    ADD FOREIGN KEY (categoryid)
    REFERENCES staging."softcartDimCategory" (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS staging."softcartFactSales"
    ADD FOREIGN KEY (itemid)
    REFERENCES staging."softcartDimItem" (itemid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS staging."softcartFactSales"
    ADD FOREIGN KEY (countryid)
    REFERENCES staging."softcartDimCountry" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;